<?php

namespace AllSrvs\Base\Entity;

use AllSrvs\Base\Format\DateTime\DateTimeConverter;

class ModeledEntity extends Entity
{
    protected array $modelFields = [];

    public function __construct(array $modelFields, array $value)
    {
        $this->modelFields = $modelFields;
        parent::__construct($value);
    }

    public function setModelFields($fields)
    {
        $this->modelFields = $fields;
    }

    public function __set($name, $value)
    {
        $this->validateProperty($name, $value);
        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    protected function validateProperty(string $name, $value): void
    {
        // Check if field exists
        if(!array_key_exists($name, $this->modelFields)) {
            throw new \InvalidArgumentException('Field does not exist');
        }

        // Check if value is nullable
        $modelField = $this->modelFields[$name];
        if($modelField->isNullable && is_null($value)) {
            return;
        }

        switch ($modelField->type) {
            case 'int':
                if(!is_int($value)) {
                    throw new \InvalidArgumentException('Value must be an integer');
                }
                break;
            case 'float':
                if(!is_float($value)) {
                    throw new \InvalidArgumentException('Value must be a float');
                }
                break;
            case 'string':
                if(!is_string($value)) {
                    throw new \InvalidArgumentException('Value must be a string');
                }
                break;
            case 'date':
            case 'datetime':
                if(DateTimeConverter::convertFromSupportedDateTimeFormat($value) === null) {
                    throw new \InvalidArgumentException('Value must be a supported date or date/time format');
                }
                break;
            case 'bool':
                if(!is_bool($value)) {
                    throw new \InvalidArgumentException('Value must be a boolean');
                }
                break;
            case 'array':
                if(!is_array($value)) {
                    throw new \InvalidArgumentException('Value must be an array');
                }
                break;
            case 'entity':
                if(!is_array($value) || array_keys($value) === range(0, count($value) - 1)) {
                    throw new \InvalidArgumentException('Value must be an associative array');
                }
                break;
            default:
                throw new \InvalidArgumentException('Invalid field type');
        }
    }
}